
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Data.Configs.Attr
{ 
    /// <summary>
    /// 属性类型
    /// </summary>
    [System.Flags]
    public enum AttributeType
    {
        /// <summary>
        /// 空
        /// </summary>
        Null = 0,
        /// <summary>
        /// 战斗力
        /// </summary>
        Power = 100,
        /// <summary>
        /// 攻击
        /// </summary>
        Atk = 101,
        /// <summary>
        /// 生命上限
        /// </summary>
        HpMax = 102,
        /// <summary>
        /// 防御
        /// </summary>
        Defense = 103,
        /// <summary>
        /// 速度
        /// </summary>
        Speed = 104,
        /// <summary>
        /// 当前生命
        /// </summary>
        Hp = 105,
        /// <summary>
        /// 攻击%
        /// </summary>
        AtkPct = 1001,
        /// <summary>
        /// 生命%
        /// </summary>
        HpPct = 1002,
        /// <summary>
        /// 防御%
        /// </summary>
        DefensePct = 1003,
        /// <summary>
        /// 速度%
        /// </summary>
        SpeedPct = 1004,
        /// <summary>
        /// 击晕
        /// </summary>
        Stun = 2001,
        /// <summary>
        /// 暴击
        /// </summary>
        Crit = 2002,
        /// <summary>
        /// 连击
        /// </summary>
        Combo = 2003,
        /// <summary>
        /// 闪避
        /// </summary>
        Dodge = 2004,
        /// <summary>
        /// 反击
        /// </summary>
        Counter = 2005,
        /// <summary>
        /// 吸血
        /// </summary>
        Lifesteal = 2006,
        /// <summary>
        /// 抵抗击晕
        /// </summary>
        StunResist = 2007,
        /// <summary>
        /// 抵抗暴击
        /// </summary>
        CritResist = 2008,
        /// <summary>
        /// 抵抗连击
        /// </summary>
        ComboResist = 2009,
        /// <summary>
        /// 抵抗闪避
        /// </summary>
        DodgeResist = 2010,
        /// <summary>
        /// 抵抗反击
        /// </summary>
        CounterResist = 2011,
        /// <summary>
        /// 抵抗吸血
        /// </summary>
        LifestealResist = 2012,
        /// <summary>
        /// 最终增伤
        /// </summary>
        FinalDamageBoost = 3001,
        /// <summary>
        /// 最终减伤
        /// </summary>
        FinalDamageReduction = 3002,
        /// <summary>
        /// 强化暴伤
        /// </summary>
        CritDamageBoost = 3003,
        /// <summary>
        /// 弱化暴伤
        /// </summary>
        CritDamageReduction = 3004,
        /// <summary>
        /// 强化治疗
        /// </summary>
        HealingBoost = 3005,
        /// <summary>
        /// 弱化治疗
        /// </summary>
        HealingReduction = 3006,
        /// <summary>
        /// 强化机宠
        /// </summary>
        MechanicalPetBoost = 3007,
        /// <summary>
        /// 弱化机宠
        /// </summary>
        MechanicalPetReduction = 3008,
        /// <summary>
        /// 强化战斗属性
        /// </summary>
        CombatStatBoost = 3009,
        /// <summary>
        /// 无视战斗属性
        /// </summary>
        CombatStatIgnore = 3010,
        /// <summary>
        /// 强化战斗抗性
        /// </summary>
        CombatResistBoost = 3011,
        /// <summary>
        /// 无视战斗抗性
        /// </summary>
        CombatResistIgnore = 3012,
        /// <summary>
        /// 强化合成兽伤害
        /// </summary>
        ChimeraDamageBoost = 3013,
        /// <summary>
        /// 弱化合成兽伤害
        /// </summary>
        ChimeraDamageReduction = 3014,
        /// <summary>
        /// 格挡
        /// </summary>
        Block = 3015,
        /// <summary>
        /// 抗格挡
        /// </summary>
        BlockResist = 3016,
        /// <summary>
        /// 破甲
        /// </summary>
        ArmorBreak = 3017,
        /// <summary>
        /// 抗破甲
        /// </summary>
        ArmorBreakResist = 3018,
        /// <summary>
        /// 是否晕眩
        /// </summary>
        IsStun = 4001,
        /// <summary>
        /// 是否冰冻
        /// </summary>
        IsFreeze = 4002,
        /// <summary>
        /// 怒气上限
        /// </summary>
        AngerMax = 5001,
        /// <summary>
        /// 怒气当前值
        /// </summary>
        Anger = 5002,
    }

} 

