
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Attr
{
/// <summary>
/// 属性键值对
/// </summary>
public sealed partial class AttributePair : Luban.BeanBase
{
    public AttributePair(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = (Attr.AttributeType)_buf["id"].AsInt; }
        { if(!_buf["value"].IsNumber) { throw new SerializationException(); }  Value = _buf["value"]; }
    }

    public static AttributePair DeserializeAttributePair(JSONNode _buf)
    {
        return new Attr.AttributePair(_buf);
    }

    /// <summary>
    /// 属性类型
    /// </summary>
    public readonly Attr.AttributeType Id;
    /// <summary>
    /// 属性值
    /// </summary>
    public readonly long Value;
   
    public const int __ID__ = 518593113;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "value:" + Value + ","
        + "}";
    }
}
}

