
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Attr
{
public sealed partial class AttributeCfg : Luban.BeanBase
{
    public AttributeCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = (Attr.AttributeType)_buf["id"].AsInt; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["power"].IsNumber) { throw new SerializationException(); }  Power = _buf["power"]; }
        { if(!_buf["group"].IsNumber) { throw new SerializationException(); }  Group = (Attr.GroupType)_buf["group"].AsInt; }
        { if(!_buf["valueType"].IsNumber) { throw new SerializationException(); }  ValueType = (Attr.ValueType)_buf["valueType"].AsInt; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["minValue"].IsNumber) { throw new SerializationException(); }  MinValue = _buf["minValue"]; }
        { if(!_buf["maxValue"].IsNumber) { throw new SerializationException(); }  MaxValue = _buf["maxValue"]; }
    }

    public static AttributeCfg DeserializeAttributeCfg(JSONNode _buf)
    {
        return new Attr.AttributeCfg(_buf);
    }

    /// <summary>
    /// 属性ID
    /// </summary>
    public readonly Attr.AttributeType Id;
    /// <summary>
    /// 属性名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 战力系数
    /// </summary>
    public readonly float Power;
    /// <summary>
    /// 属性分组
    /// </summary>
    public readonly Attr.GroupType Group;
    /// <summary>
    /// 数值类型
    /// </summary>
    public readonly Attr.ValueType ValueType;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 最小值
    /// </summary>
    public readonly int MinValue;
    /// <summary>
    /// 最大值
    /// </summary>
    public readonly int MaxValue;
   
    public const int __ID__ = -1507304187;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "power:" + Power + ","
        + "group:" + Group + ","
        + "valueType:" + ValueType + ","
        + "desc:" + Desc + ","
        + "minValue:" + MinValue + ","
        + "maxValue:" + MaxValue + ","
        + "}";
    }
}
}

