
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Data.Configs.Attr
{ 
    /// <summary>
    /// 属性类型
    /// </summary>
    [System.Flags]
    public enum AttributeType
    {
        /// <summary>
        /// 空
        /// </summary>
        Null = 0,
        /// <summary>
        /// 战斗力
        /// </summary>
        Power = 100,
        /// <summary>
        /// 攻击
        /// </summary>
        Atk = 101,
        /// <summary>
        /// 生命上限
        /// </summary>
        HpMax = 102,
        /// <summary>
        /// 防御
        /// </summary>
        Defense = 103,
        /// <summary>
        /// 速度
        /// </summary>
        Speed = 104,
        /// <summary>
        /// 当前生命
        /// </summary>
        Hp = 105,
        /// <summary>
        /// 霸体
        /// </summary>
        Endure = 201,
    }

} 

