
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Data.Configs.Attr
{ 
    /// <summary>
    /// 属性分组类型
    /// </summary>
    [System.Flags]
    public enum GroupType
    {
        /// <summary>
        /// 战斗力
        /// </summary>
        Power = 0,
        /// <summary>
        /// 一级属性
        /// </summary>
        Primary = 1,
        /// <summary>
        /// 一级属性倍率
        /// </summary>
        PrimaryMultiple = 2,
        /// <summary>
        /// 效果属性
        /// </summary>
        Effect = 3,
        /// <summary>
        /// 效果抗性
        /// </summary>
        EffectResistance = 4,
        /// <summary>
        /// 二级属性
        /// </summary>
        Secondary = 5,
    }

} 

