
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Attr
{
public partial class TbAttribute
{
    private readonly System.Collections.Generic.Dictionary<Attr.AttributeType, Attr.AttributeCfg> _dataMap;
    private readonly System.Collections.Generic.List<Attr.AttributeCfg> _dataList;
    
    public TbAttribute(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<Attr.AttributeType, Attr.AttributeCfg>(count);
        _dataList = new System.Collections.Generic.List<Attr.AttributeCfg>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Attr.AttributeCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Game.Data.Configs.Attr.AttributeCfg.DeserializeAttributeCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<Attr.AttributeType, Attr.AttributeCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<Attr.AttributeCfg> DataList => _dataList;

    public Attr.AttributeCfg GetOrDefault(Attr.AttributeType key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Attr.AttributeCfg Get(Attr.AttributeType key) => _dataMap[key];
    public Attr.AttributeCfg this[Attr.AttributeType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

