
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Data.Configs.Attr
{ 
    /// <summary>
    /// 属性数值类型
    /// </summary>
    [System.Flags]
    public enum ValueType
    {
        /// <summary>
        /// 布尔值
        /// </summary>
        Null = 0,
        /// <summary>
        /// 整数
        /// </summary>
        Int = 1,
        /// <summary>
        /// 万分比
        /// </summary>
        RatioBp = 2,
    }

} 

