
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Math
{
/// <summary>
/// 权重键值对
/// </summary>
public sealed partial class Range : Luban.BeanBase
{
    public Range(JSONNode _buf) 
    {
        { if(!_buf["min"].IsNumber) { throw new SerializationException(); }  Min = _buf["min"]; }
        { if(!_buf["max"].IsNumber) { throw new SerializationException(); }  Max = _buf["max"]; }
    }

    public static Range DeserializeRange(JSONNode _buf)
    {
        return new Math.Range(_buf);
    }

    /// <summary>
    /// 最小值
    /// </summary>
    public readonly long Min;
    /// <summary>
    /// 最大值
    /// </summary>
    public readonly long Max;
   
    public const int __ID__ = -1966755113;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "min:" + Min + ","
        + "max:" + Max + ","
        + "}";
    }
}
}

