
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Data.Configs.Sys
{ 
    /// <summary>
    /// 系统类型
    /// </summary>
    public enum SystemType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 通用
        /// </summary>
        Common = 10,
        /// <summary>
        /// 通用进度加载
        /// </summary>
        GLoading = 11,
        /// <summary>
        /// 通用弹出信息
        /// </summary>
        GTips = 12,
        /// <summary>
        /// 通用弹出提示
        /// </summary>
        GAlert = 13,
        /// <summary>
        /// 通用系统介绍
        /// </summary>
        GSystemIntro = 14,
        /// <summary>
        /// 登录
        /// </summary>
        Login = 20,
        /// <summary>
        /// 登录服务器列表
        /// </summary>
        LoginServerList = 21,
        /// <summary>
        /// 适龄提示
        /// </summary>
        LoginAgeGate = 22,
        /// <summary>
        /// 公告
        /// </summary>
        Announcement = 23,
        /// <summary>
        /// 主界面
        /// </summary>
        Main = 100,
        /// <summary>
        /// 战斗
        /// </summary>
        Battle = 200,
        /// <summary>
        /// 结算
        /// </summary>
        BattleResult = 20001,
        /// <summary>
        /// 三选一
        /// </summary>
        RougueChoosen = 20002,
    }

} 

