
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Sys
{
public sealed partial class SystemCfg : Luban.BeanBase
{
    public SystemCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = (Sys.SystemType)_buf["id"].AsInt; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { var __json0 = _buf["unlockCondition"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; UnlockCondition = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  UnlockCondition[__index0++] = __v0; }   }
        { if(!_buf["unlockPopup"].IsBoolean) { throw new SerializationException(); }  UnlockPopup = _buf["unlockPopup"]; }
        { if(!_buf["group"].IsNumber) { throw new SerializationException(); }  Group = _buf["group"]; }
    }

    public static SystemCfg DeserializeSystemCfg(JSONNode _buf)
    {
        return new Sys.SystemCfg(_buf);
    }

    /// <summary>
    /// 类型
    /// </summary>
    public readonly Sys.SystemType Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 解锁条件
    /// </summary>
    public readonly int[] UnlockCondition;
    /// <summary>
    /// 解锁弹窗
    /// </summary>
    public readonly bool UnlockPopup;
    /// <summary>
    /// 分组
    /// </summary>
    public readonly int Group;
   
    public const int __ID__ = 2048899476;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "icon:" + Icon + ","
        + "unlockCondition:" + Luban.StringUtil.CollectionToString(UnlockCondition) + ","
        + "unlockPopup:" + UnlockPopup + ","
        + "group:" + Group + ","
        + "}";
    }
}
}

