
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Sys
{
public partial class TbSystem
{
    private readonly System.Collections.Generic.Dictionary<Sys.SystemType, Sys.SystemCfg> _dataMap;
    private readonly System.Collections.Generic.List<Sys.SystemCfg> _dataList;
    
    public TbSystem(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<Sys.SystemType, Sys.SystemCfg>(count);
        _dataList = new System.Collections.Generic.List<Sys.SystemCfg>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Sys.SystemCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Game.Data.Configs.Sys.SystemCfg.DeserializeSystemCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<Sys.SystemType, Sys.SystemCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<Sys.SystemCfg> DataList => _dataList;

    public Sys.SystemCfg GetOrDefault(Sys.SystemType key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Sys.SystemCfg Get(Sys.SystemType key) => _dataMap[key];
    public Sys.SystemCfg this[Sys.SystemType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

