
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Global
{
public sealed partial class GlobalCfg : Luban.BeanBase
{
    public GlobalCfg(JSONNode _buf) 
    {
        { if(!_buf["roleNewBox"].IsNumber) { throw new SerializationException(); }  RoleNewBox = _buf["roleNewBox"]; }
        { if(!_buf["roleBoxMax"].IsNumber) { throw new SerializationException(); }  RoleBoxMax = _buf["roleBoxMax"]; }
        { if(!_buf["roleNewJjc"].IsNumber) { throw new SerializationException(); }  RoleNewJjc = _buf["roleNewJjc"]; }
        { if(!_buf["roleLevelMax"].IsNumber) { throw new SerializationException(); }  RoleLevelMax = _buf["roleLevelMax"]; }
        { if(!_buf["equipLevelMax"].IsNumber) { throw new SerializationException(); }  EquipLevelMax = _buf["equipLevelMax"]; }
        { if(!_buf["positionUpCostItem"].IsNumber) { throw new SerializationException(); }  PositionUpCostItem = _buf["positionUpCostItem"]; }
    }

    public static GlobalCfg DeserializeGlobalCfg(JSONNode _buf)
    {
        return new Global.GlobalCfg(_buf);
    }

    /// <summary>
    /// 初始宝箱数
    /// </summary>
    public readonly int RoleNewBox;
    /// <summary>
    /// 可存最大宝箱数
    /// </summary>
    public readonly int RoleBoxMax;
    /// <summary>
    /// 初始竞技券数
    /// </summary>
    public readonly int RoleNewJjc;
    /// <summary>
    /// 初始角色等级上限
    /// </summary>
    public readonly int RoleLevelMax;
    /// <summary>
    /// 最大装备等级
    /// </summary>
    public readonly int EquipLevelMax;
    /// <summary>
    /// 阵地充能消耗道具
    /// </summary>
    public readonly int PositionUpCostItem;
   
    public const int __ID__ = -471398090;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "roleNewBox:" + RoleNewBox + ","
        + "roleBoxMax:" + RoleBoxMax + ","
        + "roleNewJjc:" + RoleNewJjc + ","
        + "roleLevelMax:" + RoleLevelMax + ","
        + "equipLevelMax:" + EquipLevelMax + ","
        + "positionUpCostItem:" + PositionUpCostItem + ","
        + "}";
    }
}
}

