
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Global
{
public sealed partial class LocalizationCfg : Luban.BeanBase
{
    public LocalizationCfg(JSONNode _buf) 
    {
        { if(!_buf["key"].IsString) { throw new SerializationException(); }  Key = _buf["key"]; }
        { if(!_buf["zh"].IsString) { throw new SerializationException(); }  Zh = _buf["zh"]; }
        { if(!_buf["zh_tw"].IsString) { throw new SerializationException(); }  ZhTw = _buf["zh_tw"]; }
        { if(!_buf["en"].IsString) { throw new SerializationException(); }  En = _buf["en"]; }
        { if(!_buf["jp"].IsString) { throw new SerializationException(); }  Jp = _buf["jp"]; }
    }

    public static LocalizationCfg DeserializeLocalizationCfg(JSONNode _buf)
    {
        return new Global.LocalizationCfg(_buf);
    }

    /// <summary>
    /// 键
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 中文
    /// </summary>
    public readonly string Zh;
    /// <summary>
    /// 繁体中文
    /// </summary>
    public readonly string ZhTw;
    /// <summary>
    /// 英文
    /// </summary>
    public readonly string En;
    /// <summary>
    /// 日文
    /// </summary>
    public readonly string Jp;
   
    public const int __ID__ = 1372303040;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "zh:" + Zh + ","
        + "zhTw:" + ZhTw + ","
        + "en:" + En + ","
        + "jp:" + Jp + ","
        + "}";
    }
}
}

