
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Global
{
public partial class TbGlobal
{
    private readonly System.Collections.Generic.Dictionary<int, Global.GlobalCfg> _dataMap;
    private readonly System.Collections.Generic.List<Global.GlobalCfg> _dataList;
    
    public TbGlobal(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Global.GlobalCfg>(count);
        _dataList = new System.Collections.Generic.List<Global.GlobalCfg>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Global.GlobalCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Game.Data.Configs.Global.GlobalCfg.DeserializeGlobalCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.RoleNewBox, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Global.GlobalCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<Global.GlobalCfg> DataList => _dataList;

    public Global.GlobalCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Global.GlobalCfg Get(int key) => _dataMap[key];
    public Global.GlobalCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

