
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Global
{
public partial class TbLocalization
{
    private readonly System.Collections.Generic.Dictionary<string, Global.LocalizationCfg> _dataMap;
    private readonly System.Collections.Generic.List<Global.LocalizationCfg> _dataList;
    
    public TbLocalization(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, Global.LocalizationCfg>(count);
        _dataList = new System.Collections.Generic.List<Global.LocalizationCfg>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Global.LocalizationCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Game.Data.Configs.Global.LocalizationCfg.DeserializeLocalizationCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, Global.LocalizationCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<Global.LocalizationCfg> DataList => _dataList;

    public Global.LocalizationCfg GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Global.LocalizationCfg Get(string key) => _dataMap[key];
    public Global.LocalizationCfg this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

