
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Animal
{
public sealed partial class AnimalCfg : Luban.BeanBase
{
    public AnimalCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["gene"].IsNumber) { throw new SerializationException(); }  Gene = (Gene.GeneType)_buf["gene"].AsInt; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { var __json0 = _buf["product"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Product = new Item.ItemPair[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { Item.ItemPair __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::Game.Data.Configs.Item.ItemPair.DeserializeItemPair(__e0);  }  Product[__index0++] = __v0; }   }
        { if(!_buf["productInterval"].IsObject) { throw new SerializationException(); }  ProductInterval = global::Game.Data.Configs.Math.Range.DeserializeRange(_buf["productInterval"]);  }
        { if(!_buf["lifetime"].IsNumber) { throw new SerializationException(); }  Lifetime = _buf["lifetime"]; }
    }

    public static AnimalCfg DeserializeAnimalCfg(JSONNode _buf)
    {
        return new Animal.AnimalCfg(_buf);
    }

    /// <summary>
    /// 动物id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 动物类型
    /// </summary>
    public readonly Gene.GeneType Gene;
    /// <summary>
    /// 动物名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 产出
    /// </summary>
    public readonly Item.ItemPair[] Product;
    /// <summary>
    /// 产出间隔
    /// </summary>
    public readonly Math.Range ProductInterval;
    /// <summary>
    /// 存活时间
    /// </summary>
    public readonly int Lifetime;
   
    public const int __ID__ = 1848173398;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Product) { _e?.ResolveRef(tables); }
        ProductInterval?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "gene:" + Gene + ","
        + "name:" + Name + ","
        + "product:" + Luban.StringUtil.CollectionToString(Product) + ","
        + "productInterval:" + ProductInterval + ","
        + "lifetime:" + Lifetime + ","
        + "}";
    }
}
}

