
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Animal
{
public partial class TbAnimal
{
    private readonly System.Collections.Generic.Dictionary<int, Animal.AnimalCfg> _dataMap;
    private readonly System.Collections.Generic.List<Animal.AnimalCfg> _dataList;
    
    public TbAnimal(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Animal.AnimalCfg>(count);
        _dataList = new System.Collections.Generic.List<Animal.AnimalCfg>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Animal.AnimalCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Game.Data.Configs.Animal.AnimalCfg.DeserializeAnimalCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Animal.AnimalCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<Animal.AnimalCfg> DataList => _dataList;

    public Animal.AnimalCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Animal.AnimalCfg Get(int key) => _dataMap[key];
    public Animal.AnimalCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

