
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Battle
{
public sealed partial class AddBuffEffectCfg : Luban.BeanBase
{
    public AddBuffEffectCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["buffId"].IsNumber) { throw new SerializationException(); }  BuffId = _buf["buffId"]; }
        { if(!_buf["durationOverrideMs"].IsNumber) { throw new SerializationException(); }  DurationOverrideMs = _buf["durationOverrideMs"]; }
        { if(!_buf["stack"].IsNumber) { throw new SerializationException(); }  Stack = _buf["stack"]; }
    }

    public static AddBuffEffectCfg DeserializeAddBuffEffectCfg(JSONNode _buf)
    {
        return new Battle.AddBuffEffectCfg(_buf);
    }

    /// <summary>
    /// 效果id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 效果名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// BuffId
    /// </summary>
    public readonly int BuffId;
    /// <summary>
    /// 覆盖持续时间毫秒
    /// </summary>
    public readonly int DurationOverrideMs;
    /// <summary>
    /// 增加层数
    /// </summary>
    public readonly int Stack;
   
    public const int __ID__ = -122498731;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "buffId:" + BuffId + ","
        + "durationOverrideMs:" + DurationOverrideMs + ","
        + "stack:" + Stack + ","
        + "}";
    }
}
}

