
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Battle
{
/// <summary>
/// 战斗范围形状
/// </summary>
public sealed partial class BattleShapeDesc : Luban.BeanBase
{
    public BattleShapeDesc(JSONNode _buf) 
    {
        { if(!_buf["shapeType"].IsNumber) { throw new SerializationException(); }  ShapeType = (Battle.SkillShapeType)_buf["shapeType"].AsInt; }
        { if(!_buf["radius"].IsNumber) { throw new SerializationException(); }  Radius = _buf["radius"]; }
        { if(!_buf["width"].IsNumber) { throw new SerializationException(); }  Width = _buf["width"]; }
        { if(!_buf["length"].IsNumber) { throw new SerializationException(); }  Length = _buf["length"]; }
        { if(!_buf["angleDeg"].IsNumber) { throw new SerializationException(); }  AngleDeg = _buf["angleDeg"]; }
        { if(!_buf["offsetX"].IsNumber) { throw new SerializationException(); }  OffsetX = _buf["offsetX"]; }
        { if(!_buf["offsetY"].IsNumber) { throw new SerializationException(); }  OffsetY = _buf["offsetY"]; }
    }

    public static BattleShapeDesc DeserializeBattleShapeDesc(JSONNode _buf)
    {
        return new Battle.BattleShapeDesc(_buf);
    }

    public readonly Battle.SkillShapeType ShapeType;
    public readonly float Radius;
    public readonly float Width;
    public readonly float Length;
    public readonly float AngleDeg;
    public readonly float OffsetX;
    public readonly float OffsetY;
   
    public const int __ID__ = 2053196484;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "shapeType:" + ShapeType + ","
        + "radius:" + Radius + ","
        + "width:" + Width + ","
        + "length:" + Length + ","
        + "angleDeg:" + AngleDeg + ","
        + "offsetX:" + OffsetX + ","
        + "offsetY:" + OffsetY + ","
        + "}";
    }
}
}

