
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Battle
{
/// <summary>
/// 强化引用
/// </summary>
public sealed partial class BattleModifierRef : Luban.BeanBase
{
    public BattleModifierRef(JSONNode _buf) 
    {
        { if(!_buf["targetType"].IsNumber) { throw new SerializationException(); }  TargetType = (Battle.ModifierTargetType)_buf["targetType"].AsInt; }
        { if(!_buf["modifierType"].IsNumber) { throw new SerializationException(); }  ModifierType = _buf["modifierType"]; }
        { if(!_buf["value"].IsObject) { throw new SerializationException(); }  Value = global::Game.Data.Configs.Battle.ModifierValue.DeserializeModifierValue(_buf["value"]);  }
        { if(!_buf["effect"].IsObject) { throw new SerializationException(); }  Effect = global::Game.Data.Configs.Battle.EffectRef.DeserializeEffectRef(_buf["effect"]);  }
    }

    public static BattleModifierRef DeserializeBattleModifierRef(JSONNode _buf)
    {
        return new Battle.BattleModifierRef(_buf);
    }

    /// <summary>
    /// 目标类型
    /// </summary>
    public readonly Battle.ModifierTargetType TargetType;
    /// <summary>
    /// 目标对应的强化类型
    /// </summary>
    public readonly int ModifierType;
    /// <summary>
    /// 强化数值
    /// </summary>
    public readonly Battle.ModifierValue Value;
    /// <summary>
    /// 可选效果
    /// </summary>
    public readonly Battle.EffectRef Effect;
   
    public const int __ID__ = -242383186;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Value?.ResolveRef(tables);
        Effect?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "targetType:" + TargetType + ","
        + "modifierType:" + ModifierType + ","
        + "value:" + Value + ","
        + "effect:" + Effect + ","
        + "}";
    }
}
}

