
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Data.Configs.Battle
{ 
    /// <summary>
    /// Buff叠加规则
    /// </summary>
    public enum BuffStackMode
    {
        /// <summary>
        /// 刷新持续时间
        /// </summary>
        Refresh = 1,
        /// <summary>
        /// 只增加层数
        /// </summary>
        Stack = 2,
        /// <summary>
        /// 刷新时间并增加层数
        /// </summary>
        RefreshAndStack = 3,
        /// <summary>
        /// 替换旧Buff
        /// </summary>
        Replace = 4,
    }

} 

