
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Battle
{
public sealed partial class BuffCfg : Luban.BeanBase
{
    public BuffCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["durationMs"].IsNumber) { throw new SerializationException(); }  DurationMs = _buf["durationMs"]; }
        { if(!_buf["maxStack"].IsNumber) { throw new SerializationException(); }  MaxStack = _buf["maxStack"]; }
        { if(!_buf["stackMode"].IsNumber) { throw new SerializationException(); }  StackMode = (Battle.BuffStackMode)_buf["stackMode"].AsInt; }
        { if(!_buf["tickMs"].IsNumber) { throw new SerializationException(); }  TickMs = _buf["tickMs"]; }
        { var __json0 = _buf["attrs"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Attrs = new Attr.AttributePair[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { Attr.AttributePair __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::Game.Data.Configs.Attr.AttributePair.DeserializeAttributePair(__e0);  }  Attrs[__index0++] = __v0; }   }
        { var __json0 = _buf["tickEffects"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; TickEffects = new Battle.EffectRef[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { Battle.EffectRef __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::Game.Data.Configs.Battle.EffectRef.DeserializeEffectRef(__e0);  }  TickEffects[__index0++] = __v0; }   }
        { var __json0 = _buf["beginEffects"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; BeginEffects = new Battle.EffectRef[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { Battle.EffectRef __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::Game.Data.Configs.Battle.EffectRef.DeserializeEffectRef(__e0);  }  BeginEffects[__index0++] = __v0; }   }
        { var __json0 = _buf["endEffects"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; EndEffects = new Battle.EffectRef[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { Battle.EffectRef __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::Game.Data.Configs.Battle.EffectRef.DeserializeEffectRef(__e0);  }  EndEffects[__index0++] = __v0; }   }
    }

    public static BuffCfg DeserializeBuffCfg(JSONNode _buf)
    {
        return new Battle.BuffCfg(_buf);
    }

    /// <summary>
    /// BuffId
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Buff名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 持续毫秒
    /// </summary>
    public readonly int DurationMs;
    /// <summary>
    /// 最大层数
    /// </summary>
    public readonly int MaxStack;
    /// <summary>
    /// 叠加规则
    /// </summary>
    public readonly Battle.BuffStackMode StackMode;
    /// <summary>
    /// 周期毫秒
    /// </summary>
    public readonly int TickMs;
    /// <summary>
    /// 属性修改
    /// </summary>
    public readonly Attr.AttributePair[] Attrs;
    /// <summary>
    /// 周期效果
    /// </summary>
    public readonly Battle.EffectRef[] TickEffects;
    /// <summary>
    /// 开始效果
    /// </summary>
    public readonly Battle.EffectRef[] BeginEffects;
    /// <summary>
    /// 结束效果
    /// </summary>
    public readonly Battle.EffectRef[] EndEffects;
   
    public const int __ID__ = 942931931;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Attrs) { _e?.ResolveRef(tables); }
        foreach (var _e in TickEffects) { _e?.ResolveRef(tables); }
        foreach (var _e in BeginEffects) { _e?.ResolveRef(tables); }
        foreach (var _e in EndEffects) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "durationMs:" + DurationMs + ","
        + "maxStack:" + MaxStack + ","
        + "stackMode:" + StackMode + ","
        + "tickMs:" + TickMs + ","
        + "attrs:" + Luban.StringUtil.CollectionToString(Attrs) + ","
        + "tickEffects:" + Luban.StringUtil.CollectionToString(TickEffects) + ","
        + "beginEffects:" + Luban.StringUtil.CollectionToString(BeginEffects) + ","
        + "endEffects:" + Luban.StringUtil.CollectionToString(EndEffects) + ","
        + "}";
    }
}
}

