
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Battle
{
public sealed partial class DamageEffectCfg : Luban.BeanBase
{
    public DamageEffectCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["attr"].IsNumber) { throw new SerializationException(); }  Attr = (Attr.AttributeType)_buf["attr"].AsInt; }
        { if(!_buf["ratio"].IsNumber) { throw new SerializationException(); }  Ratio = _buf["ratio"]; }
        { if(!_buf["fixedValue"].IsNumber) { throw new SerializationException(); }  FixedValue = _buf["fixedValue"]; }
        { if(!_buf["damageElement"].IsNumber) { throw new SerializationException(); }  DamageElement = _buf["damageElement"]; }
        { if(!_buf["canCrit"].IsBoolean) { throw new SerializationException(); }  CanCrit = _buf["canCrit"]; }
        { if(!_buf["hitCount"].IsNumber) { throw new SerializationException(); }  HitCount = _buf["hitCount"]; }
    }

    public static DamageEffectCfg DeserializeDamageEffectCfg(JSONNode _buf)
    {
        return new Battle.DamageEffectCfg(_buf);
    }

    /// <summary>
    /// 效果id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 效果名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 取值属性
    /// </summary>
    public readonly Attr.AttributeType Attr;
    /// <summary>
    /// 属性倍率
    /// </summary>
    public readonly long Ratio;
    /// <summary>
    /// 固定伤害
    /// </summary>
    public readonly long FixedValue;
    /// <summary>
    /// 伤害元素
    /// </summary>
    public readonly int DamageElement;
    /// <summary>
    /// 是否暴击
    /// </summary>
    public readonly bool CanCrit;
    /// <summary>
    /// 最大命中数
    /// </summary>
    public readonly int HitCount;
   
    public const int __ID__ = 940490030;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "attr:" + Attr + ","
        + "ratio:" + Ratio + ","
        + "fixedValue:" + FixedValue + ","
        + "damageElement:" + DamageElement + ","
        + "canCrit:" + CanCrit + ","
        + "hitCount:" + HitCount + ","
        + "}";
    }
}
}

