
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Battle
{
/// <summary>
/// 效果引用
/// </summary>
public sealed partial class EffectRef : Luban.BeanBase
{
    public EffectRef(JSONNode _buf) 
    {
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (Battle.EffectType)_buf["type"].AsInt; }
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["value"].IsNumber) { throw new SerializationException(); }  Value = _buf["value"]; }
    }

    public static EffectRef DeserializeEffectRef(JSONNode _buf)
    {
        return new Battle.EffectRef(_buf);
    }

    public readonly Battle.EffectType Type;
    public readonly int Id;
    public readonly long Value;
   
    public const int __ID__ = -1578937460;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "type:" + Type + ","
        + "id:" + Id + ","
        + "value:" + Value + ","
        + "}";
    }
}
}

