
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Data.Configs.Battle
{ 
    /// <summary>
    /// 效果类型
    /// </summary>
    public enum EffectType
    {
        /// <summary>
        /// 无
        /// </summary>
        Null = 0,
        /// <summary>
        /// 造成伤害
        /// </summary>
        Damage = 1,
        /// <summary>
        /// 回复生命
        /// </summary>
        Heal = 2,
        /// <summary>
        /// 添加Buff
        /// </summary>
        AddBuff = 3,
        /// <summary>
        /// 发射抛射物
        /// </summary>
        Projectile = 4,
    }

} 

