
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Data.Configs.Battle
{ 
    /// <summary>
    /// ????
    /// </summary>
    public enum EnhancementRarity
    {
        /// <summary>
        /// ??
        /// </summary>
        Common = 0,
        /// <summary>
        /// ??
        /// </summary>
        Rare = 1,
        /// <summary>
        /// ??
        /// </summary>
        Epic = 2,
        /// <summary>
        /// ??
        /// </summary>
        Legendary = 3,
    }

} 

