
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Battle
{
public sealed partial class HealEffectCfg : Luban.BeanBase
{
    public HealEffectCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["attr"].IsNumber) { throw new SerializationException(); }  Attr = (Attr.AttributeType)_buf["attr"].AsInt; }
        { if(!_buf["ratio"].IsNumber) { throw new SerializationException(); }  Ratio = _buf["ratio"]; }
        { if(!_buf["fixedValue"].IsNumber) { throw new SerializationException(); }  FixedValue = _buf["fixedValue"]; }
        { if(!_buf["canCrit"].IsBoolean) { throw new SerializationException(); }  CanCrit = _buf["canCrit"]; }
    }

    public static HealEffectCfg DeserializeHealEffectCfg(JSONNode _buf)
    {
        return new Battle.HealEffectCfg(_buf);
    }

    /// <summary>
    /// 效果id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 效果名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 取值属性
    /// </summary>
    public readonly Attr.AttributeType Attr;
    /// <summary>
    /// 属性倍率
    /// </summary>
    public readonly long Ratio;
    /// <summary>
    /// 固定回血
    /// </summary>
    public readonly long FixedValue;
    /// <summary>
    /// 是否暴击
    /// </summary>
    public readonly bool CanCrit;
   
    public const int __ID__ = 785079637;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "attr:" + Attr + ","
        + "ratio:" + Ratio + ","
        + "fixedValue:" + FixedValue + ","
        + "canCrit:" + CanCrit + ","
        + "}";
    }
}
}

