
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Data.Configs.Battle
{ 
    /// <summary>
    /// 强化目标类型
    /// </summary>
    public enum ModifierTargetType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 单位强化
        /// </summary>
        Unit = 1,
        /// <summary>
        /// 技能强化
        /// </summary>
        Skill = 2,
        /// <summary>
        /// 弹道强化
        /// </summary>
        Projectile = 3,
        /// <summary>
        /// 触发器强化
        /// </summary>
        Trigger = 4,
    }

} 

