
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Data.Configs.Battle
{ 
    /// <summary>
    /// ??????
    /// </summary>
    public enum ModifierSourceType
    {
        /// <summary>
        /// ?
        /// </summary>
        None = 0,
        /// <summary>
        /// ????
        /// </summary>
        RogueEnhancement = 1,
        /// <summary>
        /// Buff
        /// </summary>
        Buff = 2,
        /// <summary>
        /// ??
        /// </summary>
        Aura = 3,
        /// <summary>
        /// ??
        /// </summary>
        Equipment = 4,
        /// <summary>
        /// ????
        /// </summary>
        TemporaryEffect = 5,
        /// <summary>
        /// ???
        /// </summary>
        Trigger = 6,
    }

} 

