
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Battle
{
/// <summary>
/// 强化数值
/// </summary>
public sealed partial class ModifierValue : Luban.BeanBase
{
    public ModifierValue(JSONNode _buf) 
    {
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (Attr.ValueType)_buf["type"].AsInt; }
        { if(!_buf["intValue"].IsNumber) { throw new SerializationException(); }  IntValue = _buf["intValue"]; }
    }

    public static ModifierValue DeserializeModifierValue(JSONNode _buf)
    {
        return new Battle.ModifierValue(_buf);
    }

    /// <summary>
    /// ????
    /// </summary>
    public readonly Attr.ValueType Type;
    /// <summary>
    /// ????
    /// </summary>
    public readonly int IntValue;
   
    public const int __ID__ = 991697444;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "type:" + Type + ","
        + "intValue:" + IntValue + ","
        + "}";
    }
}
}

