
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Data.Configs.Battle
{ 
    /// <summary>
    /// 阵营筛选
    /// </summary>
    public enum ModifierCampType
    {
        /// <summary>
        /// 玩家阵营
        /// </summary>
        Player = 0,
        /// <summary>
        /// 敌方阵营
        /// </summary>
        Enemy = 1,
        /// <summary>
        /// 任意阵营
        /// </summary>
        Any = 2,
    }

} 

