
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Data.Configs.Battle
{ 
    /// <summary>
    /// ??????
    /// </summary>
    public enum ProjectileModifierType
    {
        /// <summary>
        /// ?
        /// </summary>
        None = 0,
        /// <summary>
        /// ??????
        /// </summary>
        ReplaceProjectile = 1,
        /// <summary>
        /// ??????
        /// </summary>
        ProjectilePierce = 2,
        /// <summary>
        /// ??????
        /// </summary>
        ProjectileHitArea = 3,
    }

} 

