
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Battle
{
public sealed partial class ProjectileEffectCfg : Luban.BeanBase
{
    public ProjectileEffectCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["projectileKey"].IsString) { throw new SerializationException(); }  ProjectileKey = _buf["projectileKey"]; }
        { if(!_buf["speed"].IsNumber) { throw new SerializationException(); }  Speed = _buf["speed"]; }
        { if(!_buf["radius"].IsNumber) { throw new SerializationException(); }  Radius = _buf["radius"]; }
        { if(!_buf["lifetimeMs"].IsNumber) { throw new SerializationException(); }  LifetimeMs = _buf["lifetimeMs"]; }
        { if(!_buf["pierceCount"].IsNumber) { throw new SerializationException(); }  PierceCount = _buf["pierceCount"]; }
        { if(!_buf["hitIntervalMs"].IsNumber) { throw new SerializationException(); }  HitIntervalMs = _buf["hitIntervalMs"]; }
        { if(!_buf["queryQuality"].IsNumber) { throw new SerializationException(); }  QueryQuality = (Battle.QueryQuality)_buf["queryQuality"].AsInt; }
        { var __json0 = _buf["hitEffects"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; HitEffects = new Battle.EffectRef[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { Battle.EffectRef __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::Game.Data.Configs.Battle.EffectRef.DeserializeEffectRef(__e0);  }  HitEffects[__index0++] = __v0; }   }
    }

    public static ProjectileEffectCfg DeserializeProjectileEffectCfg(JSONNode _buf)
    {
        return new Battle.ProjectileEffectCfg(_buf);
    }

    /// <summary>
    /// 效果id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 效果名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 抛射物表现key
    /// </summary>
    public readonly string ProjectileKey;
    /// <summary>
    /// 速度
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 碰撞半径
    /// </summary>
    public readonly float Radius;
    /// <summary>
    /// 存活毫秒
    /// </summary>
    public readonly int LifetimeMs;
    /// <summary>
    /// 穿透次数
    /// </summary>
    public readonly int PierceCount;
    /// <summary>
    /// 同目标命中间隔
    /// </summary>
    public readonly int HitIntervalMs;
    /// <summary>
    /// 碰撞检测质量
    /// </summary>
    public readonly Battle.QueryQuality QueryQuality;
    /// <summary>
    /// 命中效果
    /// </summary>
    public readonly Battle.EffectRef[] HitEffects;
   
    public const int __ID__ = 1049342708;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in HitEffects) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "projectileKey:" + ProjectileKey + ","
        + "speed:" + Speed + ","
        + "radius:" + Radius + ","
        + "lifetimeMs:" + LifetimeMs + ","
        + "pierceCount:" + PierceCount + ","
        + "hitIntervalMs:" + HitIntervalMs + ","
        + "queryQuality:" + QueryQuality + ","
        + "hitEffects:" + Luban.StringUtil.CollectionToString(HitEffects) + ","
        + "}";
    }
}
}

