
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Data.Configs.Battle
{ 
    /// <summary>
    /// 查询精度
    /// </summary>
    public enum QueryQuality
    {
        /// <summary>
        /// 仅当前位置
        /// </summary>
        Low = 0,
        /// <summary>
        /// 完整路径
        /// </summary>
        Mid = 1,
        /// <summary>
        /// 完整路径并取最近命中
        /// </summary>
        High = 2,
    }

} 

