
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Data.Configs.Battle
{ 
    /// <summary>
    /// Query quality
    /// </summary>
    public enum QueryQuality
    {
        /// <summary>
        /// Current position only
        /// </summary>
        Low = 0,
        /// <summary>
        /// Full path query
        /// </summary>
        Mid = 1,
        /// <summary>
        /// Full path and nearest hit
        /// </summary>
        High = 2,
    }

} 

