
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Battle
{
public sealed partial class SkillCfg : Luban.BeanBase
{
    public SkillCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["actionName"].IsString) { throw new SerializationException(); }  ActionName = _buf["actionName"]; }
        { if(!_buf["castPreMs"].IsNumber) { throw new SerializationException(); }  CastPreMs = _buf["castPreMs"]; }
        { if(!_buf["castBackMs"].IsNumber) { throw new SerializationException(); }  CastBackMs = _buf["castBackMs"]; }
        { if(!_buf["cooldownMs"].IsNumber) { throw new SerializationException(); }  CooldownMs = _buf["cooldownMs"]; }
        { if(!_buf["targetType"].IsNumber) { throw new SerializationException(); }  TargetType = (Battle.SkillTargetType)_buf["targetType"].AsInt; }
        { if(!_buf["selectType"].IsNumber) { throw new SerializationException(); }  SelectType = (Battle.TargetSelectType)_buf["selectType"].AsInt; }
        { if(!_buf["shape"].IsObject) { throw new SerializationException(); }  Shape = global::Game.Data.Configs.Battle.BattleShapeDesc.DeserializeBattleShapeDesc(_buf["shape"]);  }
        { var __json0 = _buf["effects"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Effects = new Battle.EffectRef[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { Battle.EffectRef __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::Game.Data.Configs.Battle.EffectRef.DeserializeEffectRef(__e0);  }  Effects[__index0++] = __v0; }   }
    }

    public static SkillCfg DeserializeSkillCfg(JSONNode _buf)
    {
        return new Battle.SkillCfg(_buf);
    }

    /// <summary>
    /// 技能id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 技能名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 动作名
    /// </summary>
    public readonly string ActionName;
    /// <summary>
    /// 前摇毫秒
    /// </summary>
    public readonly int CastPreMs;
    /// <summary>
    /// 后摇毫秒
    /// </summary>
    public readonly int CastBackMs;
    /// <summary>
    /// 冷却毫秒
    /// </summary>
    public readonly int CooldownMs;
    /// <summary>
    /// 目标类型
    /// </summary>
    public readonly Battle.SkillTargetType TargetType;
    /// <summary>
    /// 选敌方式
    /// </summary>
    public readonly Battle.TargetSelectType SelectType;
    /// <summary>
    /// 范围形状
    /// </summary>
    public readonly Battle.BattleShapeDesc Shape;
    /// <summary>
    /// 效果列表
    /// </summary>
    public readonly Battle.EffectRef[] Effects;
   
    public const int __ID__ = -1463362359;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Shape?.ResolveRef(tables);
        foreach (var _e in Effects) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "actionName:" + ActionName + ","
        + "castPreMs:" + CastPreMs + ","
        + "castBackMs:" + CastBackMs + ","
        + "cooldownMs:" + CooldownMs + ","
        + "targetType:" + TargetType + ","
        + "selectType:" + SelectType + ","
        + "shape:" + Shape + ","
        + "effects:" + Luban.StringUtil.CollectionToString(Effects) + ","
        + "}";
    }
}
}

