
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Battle
{
/// <summary>
/// 技能筛选器
/// </summary>
public sealed partial class SkillSelector : Luban.BeanBase
{
    public SkillSelector(JSONNode _buf) 
    {
        { if(!_buf["slotIndex"].IsNumber) { throw new SerializationException(); }  SlotIndex = _buf["slotIndex"]; }
        { var __json0 = _buf["skillIds"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; SkillIds = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  SkillIds[__index0++] = __v0; }   }
    }

    public static SkillSelector DeserializeSkillSelector(JSONNode _buf)
    {
        return new Battle.SkillSelector(_buf);
    }

    /// <summary>
    /// 技能槽位，-1表示任意
    /// </summary>
    public readonly int SlotIndex;
    /// <summary>
    /// 允许的技能id
    /// </summary>
    public readonly int[] SkillIds;
   
    public const int __ID__ = -74215782;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "slotIndex:" + SlotIndex + ","
        + "skillIds:" + Luban.StringUtil.CollectionToString(SkillIds) + ","
        + "}";
    }
}
}

