
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Data.Configs.Battle
{ 
    /// <summary>
    /// 技能形状类型
    /// </summary>
    public enum SkillShapeType
    {
        /// <summary>
        /// 无
        /// </summary>
        Null = 0,
        /// <summary>
        /// 圆形
        /// </summary>
        Circle = 1,
        /// <summary>
        /// 矩形
        /// </summary>
        Rect = 2,
        /// <summary>
        /// 扇形
        /// </summary>
        Sector = 3,
        /// <summary>
        /// 胶囊线段
        /// </summary>
        Capsule = 4,
    }

} 

