
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Data.Configs.Battle
{ 
    /// <summary>
    /// 技能强化类型
    /// </summary>
    public enum SkillModifierType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 额外弹道数量
        /// </summary>
        ProjectileNum = 1,
        /// <summary>
        /// 攻击速度
        /// </summary>
        AttackSpeed = 2,
        /// <summary>
        /// 冷却缩减
        /// </summary>
        CooldownReduction = 3,
        /// <summary>
        /// 替换弹道效果
        /// </summary>
        ReplaceProjectile = 4,
        /// <summary>
        /// 弹道穿透增量
        /// </summary>
        ProjectilePierce = 5,
        /// <summary>
        /// 弹道命中范围
        /// </summary>
        ProjectileHitArea = 6,
    }

} 

