
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Data.Configs.Battle
{ 
    /// <summary>
    /// 技能目标类型
    /// </summary>
    public enum SkillTargetType
    {
        /// <summary>
        /// 无
        /// </summary>
        Null = 0,
        /// <summary>
        /// 自身
        /// </summary>
        Self = 1,
        /// <summary>
        /// 敌方
        /// </summary>
        Enemy = 2,
        /// <summary>
        /// 友方
        /// </summary>
        Ally = 3,
        /// <summary>
        /// 指定位置
        /// </summary>
        Position = 4,
        /// <summary>
        /// 指定方向
        /// </summary>
        Direction = 5,
    }

} 

