
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Battle
{
public sealed partial class SkillEnhancementCfg : Luban.BeanBase
{
    public SkillEnhancementCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { if(!_buf["unitSelector"].IsObject) { throw new SerializationException(); }  UnitSelector = global::Game.Data.Configs.Battle.UnitSelector.DeserializeUnitSelector(_buf["unitSelector"]);  }
        { if(!_buf["skillSelector"].IsObject) { throw new SerializationException(); }  SkillSelector = global::Game.Data.Configs.Battle.SkillSelector.DeserializeSkillSelector(_buf["skillSelector"]);  }
        { if(!_buf["targetType"].IsNumber) { throw new SerializationException(); }  TargetType = (Battle.ModifierTargetType)_buf["targetType"].AsInt; }
        { if(!_buf["modifierType"].IsNumber) { throw new SerializationException(); }  ModifierType = _buf["modifierType"]; }
        { if(!_buf["value"].IsObject) { throw new SerializationException(); }  Value = global::Game.Data.Configs.Battle.ModifierValue.DeserializeModifierValue(_buf["value"]);  }
        { if(!_buf["effect"].IsObject) { throw new SerializationException(); }  Effect = global::Game.Data.Configs.Battle.EffectRef.DeserializeEffectRef(_buf["effect"]);  }
        { if(!_buf["maxStack"].IsNumber) { throw new SerializationException(); }  MaxStack = _buf["maxStack"]; }
        { if(!_buf["weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["weight"]; }
    }

    public static SkillEnhancementCfg DeserializeSkillEnhancementCfg(JSONNode _buf)
    {
        return new Battle.SkillEnhancementCfg(_buf);
    }

    /// <summary>
    /// 强化id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 单位筛选
    /// </summary>
    public readonly Battle.UnitSelector UnitSelector;
    /// <summary>
    /// 技能筛选
    /// </summary>
    public readonly Battle.SkillSelector SkillSelector;
    /// <summary>
    /// 目标类型
    /// </summary>
    public readonly Battle.ModifierTargetType TargetType;
    /// <summary>
    /// 强化类型
    /// </summary>
    public readonly int ModifierType;
    /// <summary>
    /// 数值
    /// </summary>
    public readonly Battle.ModifierValue Value;
    /// <summary>
    /// 效果
    /// </summary>
    public readonly Battle.EffectRef Effect;
    /// <summary>
    /// 最大层数
    /// </summary>
    public readonly int MaxStack;
    /// <summary>
    /// 权重
    /// </summary>
    public readonly int Weight;
   
    public const int __ID__ = 549482035;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        UnitSelector?.ResolveRef(tables);
        SkillSelector?.ResolveRef(tables);
        Value?.ResolveRef(tables);
        Effect?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "description:" + Description + ","
        + "unitSelector:" + UnitSelector + ","
        + "skillSelector:" + SkillSelector + ","
        + "targetType:" + TargetType + ","
        + "modifierType:" + ModifierType + ","
        + "value:" + Value + ","
        + "effect:" + Effect + ","
        + "maxStack:" + MaxStack + ","
        + "weight:" + Weight + ","
        + "}";
    }
}
}

