
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Data.Configs.Battle
{ 
    /// <summary>
    /// 目标选择类型
    /// </summary>
    public enum TargetSelectType
    {
        /// <summary>
        /// 无
        /// </summary>
        Null = 0,
        /// <summary>
        /// 最近目标
        /// </summary>
        Nearest = 1,
        /// <summary>
        /// 随机目标
        /// </summary>
        Random = 2,
        /// <summary>
        /// 最低血量目标
        /// </summary>
        LowestHp = 3,
        /// <summary>
        /// 以自身为中心
        /// </summary>
        SelfAround = 4,
        /// <summary>
        /// 朝向前方
        /// </summary>
        Forward = 5,
    }

} 

