
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Battle
{
public partial class TbBuff
{
    private readonly System.Collections.Generic.Dictionary<int, Battle.BuffCfg> _dataMap;
    private readonly System.Collections.Generic.List<Battle.BuffCfg> _dataList;
    
    public TbBuff(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Battle.BuffCfg>(count);
        _dataList = new System.Collections.Generic.List<Battle.BuffCfg>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Battle.BuffCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Game.Data.Configs.Battle.BuffCfg.DeserializeBuffCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Battle.BuffCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<Battle.BuffCfg> DataList => _dataList;

    public Battle.BuffCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Battle.BuffCfg Get(int key) => _dataMap[key];
    public Battle.BuffCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

