
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Battle
{
public partial class TbDamageEffect
{
    private readonly System.Collections.Generic.Dictionary<int, Battle.DamageEffectCfg> _dataMap;
    private readonly System.Collections.Generic.List<Battle.DamageEffectCfg> _dataList;
    
    public TbDamageEffect(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Battle.DamageEffectCfg>(count);
        _dataList = new System.Collections.Generic.List<Battle.DamageEffectCfg>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Battle.DamageEffectCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Game.Data.Configs.Battle.DamageEffectCfg.DeserializeDamageEffectCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Battle.DamageEffectCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<Battle.DamageEffectCfg> DataList => _dataList;

    public Battle.DamageEffectCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Battle.DamageEffectCfg Get(int key) => _dataMap[key];
    public Battle.DamageEffectCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

