
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Battle
{
public partial class TbHealEffect
{
    private readonly System.Collections.Generic.Dictionary<int, Battle.HealEffectCfg> _dataMap;
    private readonly System.Collections.Generic.List<Battle.HealEffectCfg> _dataList;
    
    public TbHealEffect(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Battle.HealEffectCfg>(count);
        _dataList = new System.Collections.Generic.List<Battle.HealEffectCfg>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Battle.HealEffectCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Game.Data.Configs.Battle.HealEffectCfg.DeserializeHealEffectCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Battle.HealEffectCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<Battle.HealEffectCfg> DataList => _dataList;

    public Battle.HealEffectCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Battle.HealEffectCfg Get(int key) => _dataMap[key];
    public Battle.HealEffectCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

