
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Battle
{
public partial class TbUnit
{
    private readonly System.Collections.Generic.Dictionary<int, Battle.UnitCfg> _dataMap;
    private readonly System.Collections.Generic.List<Battle.UnitCfg> _dataList;
    
    public TbUnit(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Battle.UnitCfg>(count);
        _dataList = new System.Collections.Generic.List<Battle.UnitCfg>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Battle.UnitCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Game.Data.Configs.Battle.UnitCfg.DeserializeUnitCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Battle.UnitCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<Battle.UnitCfg> DataList => _dataList;

    public Battle.UnitCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Battle.UnitCfg Get(int key) => _dataMap[key];
    public Battle.UnitCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

