
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Data.Configs.Battle
{ 
    /// <summary>
    /// ??????
    /// </summary>
    public enum TriggerModifierType
    {
        /// <summary>
        /// ?
        /// </summary>
        None = 0,
        /// <summary>
        /// ????
        /// </summary>
        AddEffect = 1,
        /// <summary>
        /// ????
        /// </summary>
        CastSkill = 2,
        /// <summary>
        /// ??Buff
        /// </summary>
        AddBuff = 3,
        /// <summary>
        /// ????
        /// </summary>
        RefreshCooldown = 4,
        /// <summary>
        /// ????
        /// </summary>
        AddProjectile = 5,
    }

} 

