
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Data.Configs.Battle
{ 
    /// <summary>
    /// ??????
    /// </summary>
    public enum TriggerEventType
    {
        /// <summary>
        /// ?
        /// </summary>
        None = 0,
        /// <summary>
        /// ?????
        /// </summary>
        OnSkillCast = 1,
        /// <summary>
        /// ?????
        /// </summary>
        OnProjectileHit = 2,
        /// <summary>
        /// ???
        /// </summary>
        OnKill = 3,
        /// <summary>
        /// Buff???
        /// </summary>
        OnBuffTick = 4,
        /// <summary>
        /// ????
        /// </summary>
        OnInterval = 5,
    }

} 

