
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Data.Configs.Battle
{ 
    /// <summary>
    /// 单位运行时标记
    /// </summary>
    [System.Flags]
    public enum UnitFlag
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 英雄
        /// </summary>
        Hero = 1,
        /// <summary>
        /// 放置单位
        /// </summary>
        Placed = 2,
        /// <summary>
        /// 召唤单位
        /// </summary>
        Summon = 4,
        /// <summary>
        /// 怪物
        /// </summary>
        Monster = 8,
    }

} 

