
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Battle
{
public sealed partial class UnitCfg : Luban.BeanBase
{
    public UnitCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["radius"].IsNumber) { throw new SerializationException(); }  Radius = _buf["radius"]; }
        { if(!_buf["camp"].IsNumber) { throw new SerializationException(); }  Camp = _buf["camp"]; }
        { if(!_buf["layer"].IsNumber) { throw new SerializationException(); }  Layer = _buf["layer"]; }
        { var __json0 = _buf["attrs"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Attrs = new Attr.AttributePair[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { Attr.AttributePair __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::Game.Data.Configs.Attr.AttributePair.DeserializeAttributePair(__e0);  }  Attrs[__index0++] = __v0; }   }
        { var __json0 = _buf["defaultSkills"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; DefaultSkills = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  DefaultSkills[__index0++] = __v0; }   }
        { if(!_buf["renderKey"].IsString) { throw new SerializationException(); }  RenderKey = _buf["renderKey"]; }
    }

    public static UnitCfg DeserializeUnitCfg(JSONNode _buf)
    {
        return new Battle.UnitCfg(_buf);
    }

    /// <summary>
    /// 单位id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 单位名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 碰撞半径
    /// </summary>
    public readonly float Radius;
    /// <summary>
    /// 默认阵营
    /// </summary>
    public readonly int Camp;
    /// <summary>
    /// 层级
    /// </summary>
    public readonly int Layer;
    /// <summary>
    /// 初始属性
    /// </summary>
    public readonly Attr.AttributePair[] Attrs;
    /// <summary>
    /// 默认技能
    /// </summary>
    public readonly int[] DefaultSkills;
    /// <summary>
    /// 表现资源key
    /// </summary>
    public readonly string RenderKey;
   
    public const int __ID__ = 428416266;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Attrs) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "radius:" + Radius + ","
        + "camp:" + Camp + ","
        + "layer:" + Layer + ","
        + "attrs:" + Luban.StringUtil.CollectionToString(Attrs) + ","
        + "defaultSkills:" + Luban.StringUtil.CollectionToString(DefaultSkills) + ","
        + "renderKey:" + RenderKey + ","
        + "}";
    }
}
}

