
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Data.Configs.Battle
{ 
    /// <summary>
    /// 单位定位标记
    /// </summary>
    public enum UnitRoleFlag
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 近战
        /// </summary>
        Melee = 1,
        /// <summary>
        /// 远程
        /// </summary>
        Ranged = 2,
        /// <summary>
        /// 坦克
        /// </summary>
        Tank = 4,
        /// <summary>
        /// 辅助
        /// </summary>
        Support = 8,
        /// <summary>
        /// 施法
        /// </summary>
        Caster = 16,
    }

} 

