
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Game.Data.Configs.Battle
{
/// <summary>
/// 单位筛选器
/// </summary>
public sealed partial class UnitSelector : Luban.BeanBase
{
    public UnitSelector(JSONNode _buf) 
    {
        { if(!_buf["requiredUnitFlags"].IsNumber) { throw new SerializationException(); }  RequiredUnitFlags = (Battle.UnitFlag)_buf["requiredUnitFlags"].AsInt; }
        { if(!_buf["forbiddenUnitFlags"].IsNumber) { throw new SerializationException(); }  ForbiddenUnitFlags = (Battle.UnitFlag)_buf["forbiddenUnitFlags"].AsInt; }
        { if(!_buf["requiredRoleFlags"].IsNumber) { throw new SerializationException(); }  RequiredRoleFlags = (Battle.UnitRoleFlag)_buf["requiredRoleFlags"].AsInt; }
        { if(!_buf["forbiddenRoleFlags"].IsNumber) { throw new SerializationException(); }  ForbiddenRoleFlags = (Battle.UnitRoleFlag)_buf["forbiddenRoleFlags"].AsInt; }
        { var __json0 = _buf["unitCfgIds"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; UnitCfgIds = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  UnitCfgIds[__index0++] = __v0; }   }
    }

    public static UnitSelector DeserializeUnitSelector(JSONNode _buf)
    {
        return new Battle.UnitSelector(_buf);
    }

    /// <summary>
    /// 必须拥有的单位标记
    /// </summary>
    public readonly Battle.UnitFlag RequiredUnitFlags;
    /// <summary>
    /// 禁止拥有的单位标记
    /// </summary>
    public readonly Battle.UnitFlag ForbiddenUnitFlags;
    /// <summary>
    /// 必须拥有的定位标记
    /// </summary>
    public readonly Battle.UnitRoleFlag RequiredRoleFlags;
    /// <summary>
    /// 禁止拥有的定位标记
    /// </summary>
    public readonly Battle.UnitRoleFlag ForbiddenRoleFlags;
    /// <summary>
    /// 允许的单位配置id
    /// </summary>
    public readonly int[] UnitCfgIds;
   
    public const int __ID__ = 1495551737;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "requiredUnitFlags:" + RequiredUnitFlags + ","
        + "forbiddenUnitFlags:" + ForbiddenUnitFlags + ","
        + "requiredRoleFlags:" + RequiredRoleFlags + ","
        + "forbiddenRoleFlags:" + ForbiddenRoleFlags + ","
        + "unitCfgIds:" + Luban.StringUtil.CollectionToString(UnitCfgIds) + ","
        + "}";
    }
}
}

