
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Data.Configs.Level
{ 
    /// <summary>
    /// 关卡类型
    /// </summary>
    public enum LevelType
    {
        /// <summary>
        /// 主线关卡
        /// </summary>
        Main = 1,
        /// <summary>
        /// 资源关卡
        /// </summary>
        Resource = 2,
    }

} 

