
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Data.Configs.Gene
{ 
    /// <summary>
    /// 基因类型
    /// </summary>
    public enum GeneType
    {
        /// <summary>
        /// 家养
        /// </summary>
        Home = 1,
        /// <summary>
        /// 食草
        /// </summary>
        Cao = 2,
        /// <summary>
        /// 肉食性
        /// </summary>
        Rou = 3,
        /// <summary>
        /// 鸟系
        /// </summary>
        Niao = 4,
    }

} 

