
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace Game.Data.Configs
{
public partial class Tables
{
    public Global.TbGlobal TbGlobal {get; }
    public Global.TbLocalization TbLocalization {get; }
    public Animal.TbAnimal TbAnimal {get; }
    public Battle.TbUnit TbUnit {get; }
    public Battle.TbSkill TbSkill {get; }
    public Battle.TbBuff TbBuff {get; }
    public Battle.TbDamageEffect TbDamageEffect {get; }
    public Battle.TbHealEffect TbHealEffect {get; }
    public Battle.TbAddBuffEffect TbAddBuffEffect {get; }
    public Battle.TbProjectileEffect TbProjectileEffect {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbGlobal = new Global.TbGlobal(loader("global_tbglobal"));
        TbLocalization = new Global.TbLocalization(loader("global_tblocalization"));
        TbAnimal = new Animal.TbAnimal(loader("animal_tbanimal"));
        TbUnit = new Battle.TbUnit(loader("battle_tbunit"));
        TbSkill = new Battle.TbSkill(loader("battle_tbskill"));
        TbBuff = new Battle.TbBuff(loader("battle_tbbuff"));
        TbDamageEffect = new Battle.TbDamageEffect(loader("battle_tbdamageeffect"));
        TbHealEffect = new Battle.TbHealEffect(loader("battle_tbhealeffect"));
        TbAddBuffEffect = new Battle.TbAddBuffEffect(loader("battle_tbaddbuffeffect"));
        TbProjectileEffect = new Battle.TbProjectileEffect(loader("battle_tbprojectileeffect"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbGlobal.ResolveRef(this);
        TbLocalization.ResolveRef(this);
        TbAnimal.ResolveRef(this);
        TbUnit.ResolveRef(this);
        TbSkill.ResolveRef(this);
        TbBuff.ResolveRef(this);
        TbDamageEffect.ResolveRef(this);
        TbHealEffect.ResolveRef(this);
        TbAddBuffEffect.ResolveRef(this);
        TbProjectileEffect.ResolveRef(this);
    }
}

}
